# This file was generated by GoReleaser. DO NOT EDIT.
cask "noeto-mcp" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5e283407fad051d7c5b105aae3dd1316764e421ff1f7c8f6aafe8520135305da"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0dddc0b5a5a36c770ba64c4e1733e75db0f6cd295b082381d57cb436ad30c696"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "553fb4c799e219604cc363d3b5dce131a147921c34e4e9081252cbcb123852e3"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6531f3aac2ffb553466a258fc337e53609f31c0679b270473d79466e8232427"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_linux_arm64.tar.gz"
    end
  end

  name "noeto-mcp"
  desc "An MCP server that lets an AI agent work a noeto board."
  homepage "https://noeto.online"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noeto-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noeto-mcp"]
    end
  end

  # No zap stanza required

end
