# This file was generated by GoReleaser. DO NOT EDIT.
cask "noeto-mcp" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "d994ed3cdd2385c9e1214d62749da36cee9f5f5aecf5646eef70c46f4ccb3fc4"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80c69ab76e6bf689556450cce48581130dcee47bf12eb6dd987d5cee601258a1"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "783d9d3cf7b1c4c338d8bef76a4cab13c365369e70375b719934851d0acc50da"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1b252b52c45699a35a0e71ebac7e5630fcf70a09214349b2991067e1165f363"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_linux_arm64.tar.gz"
    end
  end

  name "noeto-mcp"
  desc "An MCP server that lets an AI agent work a noeto board."
  homepage "https://noeto.online"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noeto-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noeto-mcp"]
    end
  end

  # No zap stanza required

end
