# This file was generated by GoReleaser. DO NOT EDIT.
cask "noeto-mcp" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "3982d09f9ca2e7e38ab141617be9b79ea4a431ab953a1ace9c4f6b18bd1b683d"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "69b9c3a70960f79011719ca87df29fcd79d9a7c376b53ff21c937a75feeebd04"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6bca2975d2246a0b6342f89231e5893841c7a8c0818721b3514b715a8caad360"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c27f0bd8ee7cf447b39690d3b86aaf4768575d4963e8c68db2399408b475e8b0"
      url "https://github.com/noeto-tasks/noeto-mcp/releases/download/v#{version}/noeto-mcp_linux_arm64.tar.gz"
    end
  end

  name "noeto-mcp"
  desc "An MCP server that lets an AI agent work a noeto board."
  homepage "https://noeto.online"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noeto-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noeto-mcp"]
    end
  end

  # No zap stanza required

end
